<script setup lang="ts">
import { ref, computed, watch, onUnmounted, nextTick } from "vue";

// --- Global Type Definitions for Safety ---
// Extend Window interface for Battery Status API
declare global {
  interface Navigator {
    getBattery?: () => Promise<BatteryManager>;
  }
}
interface BatteryManager extends EventTarget {
  charging: boolean;
  chargingTime: number;
  dischargingTime: number;
  level: number;
  onchargingchange: ((this: BatteryManager, ev: Event) => any) | null;
  onlevelchange: ((this: BatteryManager, ev: Event) => any) | null;
}

const log = ref<string[]>([]);
const cameraActive = ref(false);
const videoRef = ref<HTMLVideoElement | null>(null);
const mediaStream = ref<MediaStream | null>(null); // To hold the active media stream

const appendLog = (msg: string, isError = false) => {
  const status = isError ? "ERROR" : "INFO";
  const timestamp = new Date().toLocaleTimeString();
  // Simple array update triggers Svelte's reactivity
  log.value = [...log.value, `[${timestamp}] [${status}] ${msg}`];
};

// --- Push Notification Setup (Constants and Utility) ---
// Use a real, generated VAPID Public Key for testing purposes.
// NOTE: This key must be replaced with one generated by your production server.
const VAPID_PUBLIC_KEY = "YOUR_VAPID_PUBLIC_KEY_HERE"; // Replace with an actual key

const urlBase64ToUint8Array = (base64String: string) => {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/\-/g, "+")
    .replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
};

// --- Feature Implementation Logic ---

// 1. Geolocation API Demo (PWA Feature: Location Access)
const handleGeolocation = () => {
  if (!("geolocation" in navigator)) {
    return appendLog("Geolocation: Not Supported.");
  }
  appendLog("Geolocation: Requesting position...");
  navigator.geolocation.getCurrentPosition(
    (position: GeolocationPosition) => {
      appendLog(
        `Geolocation: Lat: ${position.coords.latitude}, Lon: ${position.coords.longitude}`
      );
    },
    (error: GeolocationPositionError) => {
      appendLog(`Geolocation error: ${error.message}`);
    }
  );
};

// 2. Camera API Demo (PWA Feature: Media Capture)
const handleCamera = async () => {
  if (mediaStream.value) {
    mediaStream.value.getTracks().forEach((track) => track.stop());
    mediaStream.value = null;
    cameraActive.value = false;
    return appendLog("Camera: Stream stopped.");
  }

  try {
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      return appendLog("Camera: Not Supported.");
    }
    appendLog("Camera: Requesting access...");

    // 1. Acquire the stream
    const stream = await navigator.mediaDevices.getUserMedia({ video: true });

    // 2. Set BOTH states simultaneously to trigger the v-if and the watch
    mediaStream.value = stream;
    cameraActive.value = true;

    appendLog("Camera: Access granted. Waiting for DOM render...");
  } catch (err) {
    cameraActive.value = false;
    mediaStream.value = null;
    appendLog(
      `Camera: Access denied or failed. Error: ${(err as Error).message}`
    );
  }
};

watch(mediaStream, async (newStream) => {
  if (newStream) {
    // 1. Wait for the DOM update cycle to complete.
    // This ensures v-if="cameraActive" (which relies on mediaStream)
    // has rendered the <video ref="videoRef"> element.
    await nextTick();

    if (videoRef.value) {
      // 2. Assign and Play
      videoRef.value.srcObject = newStream;
      videoRef.value
        .play()
        .catch((e) => console.error("Video play failed:", e));
      appendLog("Camera: Stream successfully connected and playing.");
    } else {
      // This should ideally not be hit, but is a good check.
      appendLog("Camera: Error connecting stream (videoRef not available).");
    }
  }
});

// Clean up stream on unmount
onUnmounted(() => {
  if (mediaStream.value) {
    mediaStream.value.getTracks().forEach((track) => track.stop());
  }
});

// 3. Vibration API Demo (PWA Feature: Haptic Feedback)
const handleVibrate = () => {
  if (!("vibrate" in navigator)) {
    return appendLog("Vibration: Not Supported.");
  }
  navigator.vibrate([200, 100, 200]);
  appendLog("Vibration: Success! Check your mobile device.");
};

// 4. Web Share API Demo
const handleWebShare = async () => {
  if (!navigator.share) {
    return appendLog("Web Share: Not Supported.");
  }

  try {
    await navigator.share({
      title: "PWA Share Demo",
      text: "Check out this awesome PWA Boilerplate!",
      url: window.location.href,
    });
    appendLog("Web Share: Successfully shared content.");
  } catch (err) {
    appendLog(
      `Web Share: Failed or user cancelled. Error: ${(err as Error).message}`
    );
  }
};

// 5. Battery Status API Demo
const handleBatteryStatus = async () => {
  if (!navigator.getBattery) {
    return appendLog("Battery Status: Not Supported.");
  }

  try {
    const battery: BatteryManager = await navigator.getBattery();
    const chargingStatus = battery.charging ? "Charging" : "Discharging";
    const level = Math.round(battery.level * 100);

    appendLog(`Battery Status: ${level}% and ${chargingStatus}.`);
  } catch (err) {
    appendLog(
      `Battery Status: Failed to read status. Error: ${(err as Error).message}`
    );
  }
};
// 6. Push Notifications
const handlePushSubscription = async () => {
  if (!("Notification" in window) || !("PushManager" in window)) {
    return appendLog("Push Notifications: Not Supported.");
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      return appendLog(`Push Notifications: Permission denied or dismissed.`);
    }
    appendLog("Push Notifications: Permission granted.");

    const registration = await navigator.serviceWorker.ready;

    const applicationServerKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);

    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: applicationServerKey,
    });

    // 4. Send subscription data to the (simulated) backend
    appendLog("Push Notifications: Successfully subscribed user.");
    // NOTE: In a real app, you would send this 'subscription' object to your server via fetch()
    console.log(subscription);
    new Notification("PWA Notification Test", {
      body: "Permission granted! This is a test notification.",
      icon: "https://placehold.co/64x64/000000/FFFFFF?text=P",
    });
  } catch (err) {
    appendLog(
      `Push Notifications: Subscription failed. Error: ${
        (err as Error).message
      }`
    );
  }
};

const handleClipboard = async () => {
  const textToCopy = `PWA Clipboard Test successful at ${new Date().toLocaleTimeString()}`;
  appendLog(`Attempting to copy text: "${textToCopy}"`);
  try {
    await navigator.clipboard.writeText(textToCopy);
    appendLog("Text copied to clipboard!");
  } catch (error) {
    // Fallback for non-secure contexts (like iframes)
    const input = document.createElement("textarea");
    input.value = textToCopy;
    document.body.appendChild(input);
    input.select();
    // fallback for "writeText" method
    document.execCommand("copy");
    document.body.removeChild(input);
    appendLog("Text copied using fallback (document.execCommand).", true);
  }
};

// --- Grid Data Setup ---
interface FeatureStatus {
  name: string;
  icon: string;
  action: () => void;
  isSupported: boolean;
  message: string;
}

const features = computed<FeatureStatus[]>(() => [
  {
    name: "Geolocation",
    icon: "📍",
    action: handleGeolocation,
    isSupported: "geolocation" in navigator,
    message: "Accesses your current latitude and longitude.",
  },
  {
    name: `Camera (${cameraActive.value ? "ON" : "OFF"})`,
    icon: cameraActive.value ? "🔴" : "📷",
    action: handleCamera,
    isSupported: !!(
      navigator.mediaDevices && navigator.mediaDevices.getUserMedia
    ),
    message: cameraActive.value
      ? "Click to stop the live video feed."
      : "Captures live video from your device camera.",
  },
  {
    name: "Vibration",
    icon: "📳",
    action: handleVibrate,
    isSupported: "vibrate" in navigator,
    message: "Vibrate the device (mobile only).",
  },
  {
    name: "Web Share",
    icon: "📤",
    action: handleWebShare,
    isSupported: !!navigator.share,
    message: "Share content with native system dialogue.",
  },

  {
    name: "Clipboard Write",
    action: handleClipboard,
    isSupported: "clipboard" in navigator && !!navigator.clipboard.writeText,
    icon: "📋",
    message: "Copies a simple text string to your device clipboard.",
    status: "Ready" as const,
  },
  {
    name: "Battery Status",
    icon: "🔋",
    action: handleBatteryStatus,
    isSupported: !!navigator.getBattery,
    message: "Get current charge level and status.",
  },
  {
    name: "Push Notifications",
    icon: "🔔",
    action: handlePushSubscription,
    isSupported: "Notification" in window && "PushManager" in window,
    message: "Request permission and register for push messages.",
  },
]);
</script>

<template>
  <div class="p-8 max-w-7xl mx-auto">
    <h1 class="text-3xl font-bold mb-8">PWA Capabilities Dashboard</h1>

    <div
      v-if="cameraActive"
      class="mb-8 border-4 border-indigo-500 rounded-lg overflow-hidden"
    >
      <video
        ref="videoRef"
        autoPlay
        playsInline
        muted
        class="w-full h-auto aspect-video object-cover"
      ></video>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        v-for="(feature, index) in features"
        :key="index"
        @click="feature.isSupported ? feature.action() : undefined"
        :class="[
          'p-6 border rounded-xl cursor-pointer transition-all shadow-lg hover:shadow-xl',
          feature.isSupported
            ? 'bg-green-200 hover:bg-green-300 ring-2 ring-indigo-200'
            : 'bg-gray-100 opacity-60 pointer-events-none',
        ]"
      >
        <div class="text-4xl mb-3">
          {{ feature.icon }}
        </div>
        <div class="font-semibold text-gray-600">
          {{ feature.name }}
        </div>
        <p class="text-sm text-gray-600 mt-1">
          {{ feature.message }}
        </p>
      </div>
    </div>

    <h2 class="text-xl font-semibold mt-10 mb-3">Event Log</h2>
    <div
      class="bg-gray-800 text-white p-4 h-40 overflow-y-scroll text-sm rounded-lg font-mono"
    >
      <div v-for="(msg, i) in log" :key="i">{{ i + 1 }}. {{ msg }}</div>
      <div v-if="log.length === 0">
        Click a feature card to see the results...
      </div>
    </div>
  </div>
</template>
